backend:
  name: git-gateway
  branch: master
media_folder: "src/assets/img/uploads"
public_folder: "img/uploads"
collections:
  - name: "generative"
    label: "Generative Art"
    folder: "src/content/generative"
    slug: "generative-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "canvas" }
      - { label: Title, name: "title", widget: "string" }
      - { label: "Published", name: "published", default: "false" }
